dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink@1.4.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.4.1'
dotenv: .env
networks:
  default: development
  development:
    verify: False
  ganache-local:
    verify: False
  rinkeby:
    verify: True
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
wallets:
  from_key: ${WEB3_PRIVATE_KEY}
